# Generated by Django 3.0 on 2023-04-14 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50)),
                ('report_date', models.DateField()),
                ('case_cnt', models.PositiveIntegerField(default=0)),
                ('active_cnt', models.PositiveIntegerField(default=0)),
                ('test_cnt', models.PositiveIntegerField(default=0)),
                ('new_case_cnt', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(max_length=100)),
                ('case_cnt', models.PositiveIntegerField(default=0)),
                ('active_cnt', models.PositiveIntegerField(default=0)),
                ('test_cnt', models.PositiveIntegerField(default=0)),
                ('new_case_cnt', models.PositiveIntegerField(default=0)),
                ('updated', models.DateField()),
            ],
        ),
    ]
