# Generated by Django 3.0 on 2023-04-14 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='state',
            name='updated',
        ),
        migrations.AddField(
            model_name='state',
            name='update_at',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
